/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EndingsRouteImport } from './routes/endings'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayMissionIdRouteImport } from './routes/play.$missionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingsRoute = EndingsRouteImport.update({
  id: '/endings',
  path: '/endings',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMissionIdRoute = PlayMissionIdRouteImport.update({
  id: '/play/$missionId',
  path: '/play/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endings': typeof EndingsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/play/$missionId': typeof PlayMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endings': typeof EndingsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/play/$missionId': typeof PlayMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endings': typeof EndingsRoute
  '/journal': typeof JournalRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/play/$missionId': typeof PlayMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/endings'
    | '/journal'
    | '/missions'
    | '/settings'
    | '/play/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/endings'
    | '/journal'
    | '/missions'
    | '/settings'
    | '/play/$missionId'
  id:
    | '__root__'
    | '/'
    | '/endings'
    | '/journal'
    | '/missions'
    | '/settings'
    | '/play/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndingsRoute: typeof EndingsRoute
  JournalRoute: typeof JournalRoute
  MissionsRoute: typeof MissionsRoute
  SettingsRoute: typeof SettingsRoute
  PlayMissionIdRoute: typeof PlayMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endings': {
      id: '/endings'
      path: '/endings'
      fullPath: '/endings'
      preLoaderRoute: typeof EndingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$missionId': {
      id: '/play/$missionId'
      path: '/play/$missionId'
      fullPath: '/play/$missionId'
      preLoaderRoute: typeof PlayMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndingsRoute: EndingsRoute,
  JournalRoute: JournalRoute,
  MissionsRoute: MissionsRoute,
  SettingsRoute: SettingsRoute,
  PlayMissionIdRoute: PlayMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
